Repository ku-ring/ku-ring-backend-web, pull requests merged in 2025-04, with the labels that each got.

#244 Feat : 로그인 유저 쿠링봇 사용 연동
  src/main/java/com/kustacks/kuring/ai/adapter/in/web/RAGQueryApiV2.java
  src/main/java/com/kustacks/kuring/ai/adapter/out/event/RAGEventAdapter.java
  src/main/java/com/kustacks/kuring/ai/application/port/in/RAGQueryUseCase.java
  src/main/java/com/kustacks/kuring/ai/application/port/out/RAGEventPort.java
  src/main/java/com/kustacks/kuring/ai/application/service/RAGQueryService.java
  src/main/java/com/kustacks/kuring/user/adapter/in/event/UserCommandEventListener.java
  src/main/java/com/kustacks/kuring/user/adapter/in/event/dto/UserDecreaseQuestionCountEvent.java
  src/main/java/com/kustacks/kuring/user/adapter/in/web/UserQueryApiV2.java
  src/main/java/com/kustacks/kuring/user/application/port/in/UserCommandUseCase.java
  src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java
  src/main/java/com/kustacks/kuring/user/application/port/in/dto/UserDecreaseQuestionCountCommand.java
  src/main/java/com/kustacks/kuring/user/application/service/UserCommandService.java
  src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java
  src/main/java/com/kustacks/kuring/user/domain/RootUser.java
  src/test/java/com/kustacks/kuring/acceptance/AiAcceptanceTest.java
  src/test/java/com/kustacks/kuring/acceptance/AiStep.java
  src/test/java/com/kustacks/kuring/acceptance/UserAcceptanceTest.java
  src/test/java/com/kustacks/kuring/acceptance/UserStep.java
Labels: ⭐ Feat

#246 [Refactor] Change status code #245
  src/main/java/com/kustacks/kuring/ai/adapter/in/web/RAGQueryApiV2.java
  src/main/java/com/kustacks/kuring/ai/adapter/out/event/RAGEventAdapter.java
  src/main/java/com/kustacks/kuring/ai/application/port/out/RAGEventPort.java
  src/main/java/com/kustacks/kuring/ai/application/service/RAGQueryService.java
  src/main/java/com/kustacks/kuring/common/dto/ResponseCodeAndMessages.java
  src/main/java/com/kustacks/kuring/notice/adapter/in/web/NoticeCommandApiV2.java
  src/main/java/com/kustacks/kuring/user/adapter/in/event/UserCommandEventListener.java
  src/main/java/com/kustacks/kuring/user/adapter/in/event/dto/UserAskedQuestionEvent.java
  src/main/java/com/kustacks/kuring/user/application/port/in/UserQueryUseCase.java
  src/main/java/com/kustacks/kuring/user/application/service/UserQueryService.java
Labels: 🔧 Refactor

#251 Feat/add ku free #250
  src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java
  src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/sanghuo_elective/KULiberalStudiesDept.java
  src/test/java/com/kustacks/kuring/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java
  src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java
Labels: ⭐ Feat

#252 [Feat] add ku free #250 (#251)
  src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java
  src/main/java/com/kustacks/kuring/worker/scrap/deptinfo/sanghuo_elective/KULiberalStudiesDept.java
  src/test/java/com/kustacks/kuring/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/kustacks/kuring/support/IntegrationTestSupport.java
  src/test/java/com/kustacks/kuring/worker/update/notice/DepartmentNoticeUpdaterTest.java
Labels: ⭐ Feat

#254 Fix : 비밀번호 초기화 인증코드 이메일 전송 방식 수정 및 검증 추가 #253
  src/main/java/com/kustacks/kuring/email/adapter/in/web/EmailCommandApiV2.java
  src/main/java/com/kustacks/kuring/email/application/service/EmailCommandService.java
  src/main/java/com/kustacks/kuring/notice/domain/DepartmentName.java
  src/test/java/com/kustacks/kuring/acceptance/EmailAcceptanceTest.java
  src/test/java/com/kustacks/kuring/acceptance/EmailStep.java
Labels: 🐛 Bug
